services:
  - type: web
    name: gestao-performance-api
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3000
